import sys

from PyQt5 import QtWidgets, QtCore,QtGui
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

from PyUi3.FWidgets import FTitleBar, FToggleButton, FAccentButton, FHomeStack, FShowCase, FWindow, FPage

class home_page(FPage):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.installEventFilter(self)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.frame = QtWidgets.QFrame(self)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 222, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel("Windows 11",self.frame)
        self.label.setAlignment(Qt.AlignCenter)
        self.verticalLayout.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(332, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton = FToggleButton("Start",self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(120, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(332, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 222, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.frame)



class page1(FPage):
    def setupUi(self, parent=None):
        super().__init__(parent=parent)
        self.verticalLayout = QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.page = QFrame()
        self.page.setStyleSheet("QWidget{Background-color:#292929}")
        self.page.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Header = QtWidgets.QLabel("hi",self.page)
        self.Header.setMaximumSize(QtCore.QSize(16777215, 51))
        self.Header.setStyleSheet("QLabel{color:rgba(255,255,255,170);font: 17px \'Segoe UI\'; margin: 2px;border:none;background-color:rgba(0,0,0,0)}")
        self.Header.setObjectName("Header")
        self.verticalLayout_3.addWidget(self.Header)
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 751, 552))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Header_2 = QtWidgets.QLabel(self.frame)
        self.Header_2.setStyleSheet("QLabel{color:rgba(255,255,255,170);font: 15px \'Segoe UI\'; margin: 2px;border:none;background-color:rgba(0,0,0,0)}")
        self.Header_2.setObjectName("Header_2")
        self.verticalLayout_2.addWidget(self.Header_2)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 71))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 71))
        self.frame_2.setStyleSheet("QFrame{background-color:#202020;\n"
"border-radius:6px;\n"
"border:1px solid #1D1D1D;}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_3.setStyleSheet("QFrame{background-color:#202020;\n"
"border:none}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(478, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_4.setStyleSheet("QFrame{background-color:#202020;\n"
"border:none}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_6.addWidget(self.frame)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 121))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Header_3 = QtWidgets.QLabel(self.frame_5)
        self.Header_3.setStyleSheet("QLabel{color:rgba(255,255,255,170);font: 15px \'Segoe UI\'; margin: 2px;border:none;background-color:rgba(0,0,0,0)}")
        self.Header_3.setObjectName("Header_3")
        self.verticalLayout_4.addWidget(self.Header_3)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 71))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 71))
        self.frame_6.setStyleSheet("QFrame{background-color:#202020;\n"
"border-radius:6px;\n"
"border:1px solid #1D1D1D;}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_7.setStyleSheet("QFrame{background-color:#202020;\n"
"border:none}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2.addWidget(self.frame_7)
        spacerItem1 = QtWidgets.QSpacerItem(478, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_8.setStyleSheet("QFrame{background-color:#202020;\n"
"border:none}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 121))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Header_4 = QtWidgets.QLabel(self.frame_9)
        self.Header_4.setStyleSheet("QLabel{color:rgba(255,255,255,170);font: 15px \'Segoe UI\'; margin: 2px;border:none;background-color:rgba(0,0,0,0)}")
        self.Header_4.setObjectName("Header_4")
        self.verticalLayout_5.addWidget(self.Header_4)
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 71))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 71))
        self.frame_10.setStyleSheet("QFrame{background-color:#202020;\n"
"border-radius:6px;\n"
"border:1px solid #1D1D1D;}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_11.setStyleSheet("QFrame{background-color:#202020;\n"
"border:none}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_3.addWidget(self.frame_11)
        spacerItem2 = QtWidgets.QSpacerItem(478, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_12.setStyleSheet("QFrame{background-color:#202020;\n"
"border:none}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_3.addWidget(self.frame_12)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.verticalLayout_6.addWidget(self.frame_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout(self.page)

class Window(FWindow):

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.resize(700,700)
        self.setMinimumSize(597, 625)
        self.setTitleBar(FTitleBar(self.main, "PyUi3"))
        self.installEventFilter(self)

        self.stack = FHomeStack(self.main)
        self.homepage = home_page()
        self.sidebar = QFrame(self.main)

        self.buttonpage = FPage(self.main)

        self.stack.addWidget(page1(self.stack))
        self.stack.addWidget(self.buttonpage)


    def eventFilter(self, obj, event):
        if event.type() == QEvent.Resize:


            if self.width() > 807:
                self.sidebar.setGeometry(0,48, 291, self.height()-48)
                self.stack.setGeometry(291, 48, self.width()-291, self.height()-48)

            else:
                self.sidebar.setGeometry(0,48, 0, self.height()-48)
                self.stack.setGeometry(0, 48, self.width(), self.height()-48)
        return super(Window, self).eventFilter(obj, event)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    demo = Window()
    demo.show()
    sys.exit(app.exec_())